/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialogos;

import com.formdev.flatlaf.intellijthemes.FlatLightFlatIJTheme;
import controller.ControllerCliente;
import model.ModelCliente;

/**
 *
 * @author DEV
 */
public class DdetalhesCliente extends javax.swing.JDialog {
    
    ModelCliente clienteD = new ModelCliente();
    ControllerCliente clienteControllerD = new ControllerCliente();
    
    private String cliNomeModal;
    private String cliEmailModal;
    private String cliTelefoneModal;
    private String cliAniversarioModal;
    private String cliCepModal;
    private String cliRuaModal;
    private String cliNumeroModal;
    private String cliBairroModal;
    private String cliCidadeModal;
    private String cliEstadoModal;
    private String cliCadastroModal;

    /**
     * Creates new form MClientes
     */
    public DdetalhesCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Dados de Cadastro do cliente - ");
//        showClient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        Mcadastro_cliente = new javax.swing.JTextField();
        Mestado_cliente = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Mcidade_araguari = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Mbairro_cliente = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Mrua_cliente = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Mnumero_cliente = new javax.swing.JTextField();
        Mcep_cliente = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        Memail_cliente = new javax.swing.JTextField();
        Mnome_cliente = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Maniversario_cliente = new javax.swing.JFormattedTextField();
        Mtelefone_cliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        Mcadastro_cliente.setEditable(false);
        Mcadastro_cliente.setFocusable(false);

        Mestado_cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        Mestado_cliente.setFocusable(false);

        jLabel17.setText("Estado:");

        jLabel18.setText("Data de Cadastro:");

        Mcidade_araguari.setEditable(false);
        Mcidade_araguari.setFocusable(false);

        jLabel19.setText("Cidade:");

        Mbairro_cliente.setEditable(false);
        Mbairro_cliente.setFocusable(false);

        jLabel20.setText("Bairro:");

        Mrua_cliente.setEditable(false);
        Mrua_cliente.setFocusable(false);

        jLabel21.setText("Rua");

        jLabel22.setText("Número:");

        Mnumero_cliente.setEditable(false);
        Mnumero_cliente.setFocusable(false);

        Mcep_cliente.setEditable(false);
        Mcep_cliente.setFocusable(false);

        jLabel23.setText("Cep:");

        Memail_cliente.setEditable(false);
        Memail_cliente.setFocusable(false);

        Mnome_cliente.setFocusable(false);

        jLabel24.setText("Nome do cliente:");

        jLabel25.setText("E-mail:");

        jLabel26.setText("Telefone:");

        jLabel27.setText("Data de aniversário:");

        Maniversario_cliente.setEditable(false);
        Maniversario_cliente.setFocusable(false);

        Mtelefone_cliente.setEditable(false);
        Mtelefone_cliente.setFocusable(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Memail_cliente)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(Mrua_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Mnumero_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(Mestado_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Mcadastro_cliente))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(Mbairro_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Mcidade_araguari))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(102, 102, 102)
                                .addComponent(jLabel27)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel23))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(315, 315, 315)
                                .addComponent(jLabel22))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(182, 182, 182)
                                .addComponent(jLabel19))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(171, 171, 171)
                                .addComponent(jLabel18)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(Mtelefone_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Maniversario_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Mcep_cliente))
                    .addComponent(Mnome_cliente))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel24)
                .addGap(6, 6, 6)
                .addComponent(Mnome_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel25)
                .addGap(6, 6, 6)
                .addComponent(Memail_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel23))
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mtelefone_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Maniversario_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcep_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mrua_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mnumero_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mbairro_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcidade_araguari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mestado_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mcadastro_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showClient(String nome) {
        Mnome_cliente.setText(nome);
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightFlatIJTheme.setup();

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DdetalhesCliente dialog = new DdetalhesCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Maniversario_cliente;
    private javax.swing.JTextField Mbairro_cliente;
    private javax.swing.JTextField Mcadastro_cliente;
    private javax.swing.JTextField Mcep_cliente;
    private javax.swing.JTextField Mcidade_araguari;
    private javax.swing.JTextField Memail_cliente;
    private javax.swing.JComboBox<String> Mestado_cliente;
    private javax.swing.JTextField Mnome_cliente;
    private javax.swing.JTextField Mnumero_cliente;
    private javax.swing.JTextField Mrua_cliente;
    private javax.swing.JTextField Mtelefone_cliente;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the cliNomeModal
     */
    public String getCliNomeModal() {
        return cliNomeModal;
    }

    /**
     * @param cliNomeModal the cliNomeModal to set
     */
    public void setCliNomeModal(String cliNomeModal) {
        this.cliNomeModal = cliNomeModal;
    }

    /**
     * @return the cliEmailModal
     */
    public String getCliEmailModal() {
        return cliEmailModal;
    }

    /**
     * @param cliEmailModal the cliEmailModal to set
     */
    public void setCliEmailModal(String cliEmailModal) {
        this.cliEmailModal = cliEmailModal;
    }

    /**
     * @return the cliTelefoneModal
     */
    public String getCliTelefoneModal() {
        return cliTelefoneModal;
    }

    /**
     * @param cliTelefoneModal the cliTelefoneModal to set
     */
    public void setCliTelefoneModal(String cliTelefoneModal) {
        this.cliTelefoneModal = cliTelefoneModal;
    }

    /**
     * @return the cliAniversarioModal
     */
    public String getCliAniversarioModal() {
        return cliAniversarioModal;
    }

    /**
     * @param cliAniversarioModal the cliAniversarioModal to set
     */
    public void setCliAniversarioModal(String cliAniversarioModal) {
        this.cliAniversarioModal = cliAniversarioModal;
    }

    /**
     * @return the cliCepModal
     */
    public String getCliCepModal() {
        return cliCepModal;
    }

    /**
     * @param cliCepModal the cliCepModal to set
     */
    public void setCliCepModal(String cliCepModal) {
        this.cliCepModal = cliCepModal;
    }

    /**
     * @return the cliRuaModal
     */
    public String getCliRuaModal() {
        return cliRuaModal;
    }

    /**
     * @param cliRuaModal the cliRuaModal to set
     */
    public void setCliRuaModal(String cliRuaModal) {
        this.cliRuaModal = cliRuaModal;
    }

    /**
     * @return the cliNumeroModal
     */
    public String getCliNumeroModal() {
        return cliNumeroModal;
    }

    /**
     * @param cliNumeroModal the cliNumeroModal to set
     */
    public void setCliNumeroModal(String cliNumeroModal) {
        this.cliNumeroModal = cliNumeroModal;
    }

    /**
     * @return the cliBairroModal
     */
    public String getCliBairroModal() {
        return cliBairroModal;
    }

    /**
     * @param cliBairroModal the cliBairroModal to set
     */
    public void setCliBairroModal(String cliBairroModal) {
        this.cliBairroModal = cliBairroModal;
    }

    /**
     * @return the cliCidadeModal
     */
    public String getCliCidadeModal() {
        return cliCidadeModal;
    }

    /**
     * @param cliCidadeModal the cliCidadeModal to set
     */
    public void setCliCidadeModal(String cliCidadeModal) {
        this.cliCidadeModal = cliCidadeModal;
    }

    /**
     * @return the cliEstadoModal
     */
    public String getCliEstadoModal() {
        return cliEstadoModal;
    }

    /**
     * @param cliEstadoModal the cliEstadoModal to set
     */
    public void setCliEstadoModal(String cliEstadoModal) {
        this.cliEstadoModal = cliEstadoModal;
    }

    /**
     * @return the cliCadastroModal
     */
    public String getCliCadastroModal() {
        return cliCadastroModal;
    }

    /**
     * @param cliCadastroModal the cliCadastroModal to set
     */
    public void setCliCadastroModal(String cliCadastroModal) {
        this.cliCadastroModal = cliCadastroModal;
    }
}
