/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialogos;

import com.formdev.flatlaf.intellijthemes.FlatLightFlatIJTheme;
import controller.ControllerVendasPagamento;
//import com.lowagie.text.Font;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.ListCellRenderer;
import model.ModelSessaoUsuario;
import model.ModelVendasPagamento;
import telas.TelaVendas;
import utils.Calculos;

/**
 *
 * @author DEV
 */
public class DvendaManual extends javax.swing.JDialog {

    ModelSessaoUsuario modelSessaoUsuario = new ModelSessaoUsuario();

    ControllerVendasPagamento ctrlVendaPagamentoCheckout = new ControllerVendasPagamento();
    ModelVendasPagamento mVendaPagamentoCheckout = new ModelVendasPagamento();

    private String cSbutotal;
    private String cDesconto;
    private String cTotal;
    private String cTotalPagar;
    private boolean finalizarCancelar;

    Calculos taxaPag = new Calculos();

    /**
     * Creates new form DvendaManual
     */
    public DvendaManual(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setaUsuarioLogado();
        setLocationRelativeTo(null);
//        CorComboBox();
        configTeclasAtalho();
        this.finalizarCancelar = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        Doperador = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        Dfuncao = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ccredito1 = new componentes.UJTextField();
        jLabel3 = new javax.swing.JLabel();
        combobox1cartaocredito = new componentes.UJComboBox();
        jLabel4 = new javax.swing.JLabel();
        cdebito2 = new componentes.UJTextField();
        jLabel5 = new javax.swing.JLabel();
        cdebito1 = new componentes.UJTextField();
        combobox1cartaodebito = new componentes.UJComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ccredito2 = new componentes.UJTextField();
        jLabel8 = new javax.swing.JLabel();
        combobox2cartaocredito = new componentes.UJComboBox();
        combobox2cartaodebito = new componentes.UJComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        picpay = new componentes.UJTextField();
        jLabel9 = new javax.swing.JLabel();
        comboxpicpay = new componentes.UJComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cparcc1 = new componentes.UJTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cparcc2 = new componentes.UJTextField();
        jLabel17 = new javax.swing.JLabel();
        dinheiro = new componentes.UJTextField();
        pix = new componentes.UJTextField();
        jLabel18 = new javax.swing.JLabel();
        cparcd1 = new componentes.UJTextField();
        cparcd2 = new componentes.UJTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        ck_subtotal = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        ck_desconto = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        ck_total = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        ck_totalPagar = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        ck_valorRestante = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Checkout");

        jPanel15.setBackground(new java.awt.Color(46, 65, 88));

        jLabel39.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel39.setText("Informações de Pagamento");
        jLabel39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel14.setBackground(new java.awt.Color(46, 65, 88));

        jLabel40.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 13)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Usuário:");

        Doperador.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        Doperador.setForeground(new java.awt.Color(255, 255, 255));
        Doperador.setText("--");

        jLabel42.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 13)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Função:");

        Dfuncao.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        Dfuncao.setForeground(new java.awt.Color(255, 255, 255));
        Dfuncao.setText("--");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Doperador)
                .addGap(18, 18, 18)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dfuncao)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Doperador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Dfuncao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 465, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Bandeira");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("1 Cartão de Crédito");

        ccredito1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ccredito1FocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Parcelas e Bandeira");

        combobox1cartaocredito.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha uma opção de Pagamento", "Mastercard", "    1 Parcela - 1.35 - Mastercard", "    2 Parcelas - 2.06 - Mastercard", "    3 Parcelas - 2.06 - Mastercard", "    4 Parcelas - 2.06 - Mastercard", "    5 Parcelas - 2.06 - Mastercard", "    6 Parcelas - 2.06 - Mastercard", "    7 Parcelas - 2.41 - Mastercard", "    8 Parcelas - 2.41 - Mastercard", "    9 Parcelas - 2.41 - Mastercard", "    10 Parcelas - 2.41 - Mastercard", "    11 Parcelas - 2.41 - Mastercard", "    12 Parcelas - 2.41 - Mastercard", "Visa", "    1 Parcela - 1.35 - Visa", "    2 Parcelas - 2.06 - Visa", "    3 Parcelas - 2.06 - Visa", "    4 Parcelas - 2.06 - Visa", "    5 Parcelas - 2.06 - Visa", "    6 Parcelas - 2.06 - Visa", "    7 Parcelas - 2.41 - Visa", "    8 Parcelas - 2.41 - Visa", "    9 Parcelas - 2.41 - Visa", "    10 Parcelas - 2.41 - Visa", "    11 Parcelas - 2.41 - Visa", "    12 Parcelas - 2.41 - Visa", "Hipercard", "    1 Parcela - 1.47 - Hipercard", "    2 Parcelas - 3.99 - Hipercard", "    3 Parcelas - 3.99 - Hipercard", "    4 Parcelas - 3.99 - Hipercard", "    5 Parcelas - 3.99 - Hipercard", "    6 Parcelas - 3.99 - Hipercard", "    7 Parcelas - 3.99 - Hipercard", "    8 Parcelas - 3.99 - Hipercard", "    9 Parcelas - 3.99 - Hipercard", "    10 Parcelas - 3.99 - Hipercard", "    11 Parcelas - 3.99 - Hipercard", "    12 Parcelas - 3.99 - Hipercard", "Elo", "    1 Parcela - 2.01 - Elo", "    2 Parcelas - 2.93 - Elo", "    3 Parcelas - 2.93 - Elo", "    4 Parcelas - 2.93 - Elo", "    5 Parcelas - 2.93 - Elo", "    6 Parcelas - 2.93 - Elo", "    7 Parcelas - 3.39 - Elo", "    8 Parcelas - 3.39 - Elo", "    9 Parcelas - 3.39 - Elo", "    10 Parcelas - 3.39 - Elo", "    11 Parcelas - 3.39 - Elo", "    12 Parcelas - 3.39 - Elo", "Cabal Vale", "    1 Parcela - 3.29 - Cabal Vale", "    2 Parcelas - 3.99 - Cabal Vale", "    3 Parcelas - 3.99 - Cabal Vale", "    4 Parcelas - 3.99 - Cabal Vale", "    5 Parcelas - 3.99 - Cabal Vale", "    6 Parcelas - 3.99 - Cabal Vale", "    7 Parcelas - 3.99 - Cabal Vale", "    8 Parcelas - 3.99 - Cabal Vale", "    9 Parcelas - 3.99 - Cabal Vale", "    10 Parcelas - 3.99 - Cabal Vale", "    11 Parcelas - 3.99 - Cabal Vale", "    12 Parcelas - 3.99 - Cabal Vale", "Amex", "    1 Parcela - 3.29 - Amex", "    2 Parcelas - 3.99 - Amex", "    3 Parcelas - 3.99 - Amex", "    4 Parcelas - 3.99 - Amex", "    5 Parcelas - 3.99 - Amex", "    6 Parcelas - 3.99 - Amex", "    7 Parcelas - 3.99 - Amex", "    8 Parcelas - 3.99 - Amex", "    9 Parcelas - 3.99 - Amex", "    10 Parcelas - 3.99 - Amex", "    11 Parcelas - 3.99 - Amex", "    12 Parcelas - 3.99 - Amex" }));
        combobox1cartaocredito.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobox1cartaocreditoItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("2 Cartão de Débito");

        cdebito2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cdebito2FocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("1 Cartão de Débito");

        cdebito1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cdebito1FocusLost(evt);
            }
        });

        combobox1cartaodebito.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha uma opção de Pagamento", "Mastercard", "    0.77 - Mastercard", "Visa", "    0.77 - Visa", "Hipercard", "    1.47 - Hipercard", "Elo", "    1.42 - Elo", "Cabal Vale", "    1.99 - Cabal Vale", "Amex", "    3.29 - Amex" }));
        combobox1cartaodebito.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobox1cartaodebitoItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Bandeira");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("2 Cartão de Crédito");

        ccredito2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ccredito2FocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Parcelas e Bandeira");

        combobox2cartaocredito.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha uma opção de Pagamento", "Mastercard", "    1 Parcela - 1.35 - Mastercard", "    2 Parcelas - 2.06 - Mastercard", "    3 Parcelas - 2.06 - Mastercard", "    4 Parcelas - 2.06 - Mastercard", "    5 Parcelas - 2.06 - Mastercard", "    6 Parcelas - 2.06 - Mastercard", "    7 Parcelas - 2.41 - Mastercard", "    8 Parcelas - 2.41 - Mastercard", "    9 Parcelas - 2.41 - Mastercard", "    10 Parcelas - 2.41 - Mastercard", "    11 Parcelas - 2.41 - Mastercard", "    12 Parcelas - 2.41 - Mastercard", "Visa", "    1 Parcela - 1.35 - Visa", "    2 Parcelas - 2.06 - Visa", "    3 Parcelas - 2.06 - Visa", "    4 Parcelas - 2.06 - Visa", "    5 Parcelas - 2.06 - Visa", "    6 Parcelas - 2.06 - Visa", "    7 Parcelas - 2.41 - Visa", "    8 Parcelas - 2.41 - Visa", "    9 Parcelas - 2.41 - Visa", "    10 Parcelas - 2.41 - Visa", "    11 Parcelas - 2.41 - Visa", "    12 Parcelas - 2.41 - Visa", "Hipercard", "    1 Parcela - 1.47 - Hipercard", "    2 Parcelas - 3.99 - Hipercard", "    3 Parcelas - 3.99 - Hipercard", "    4 Parcelas - 3.99 - Hipercard", "    5 Parcelas - 3.99 - Hipercard", "    6 Parcelas - 3.99 - Hipercard", "    7 Parcelas - 3.99 - Hipercard", "    8 Parcelas - 3.99 - Hipercard", "    9 Parcelas - 3.99 - Hipercard", "    10 Parcelas - 3.99 - Hipercard", "    11 Parcelas - 3.99 - Hipercard", "    12 Parcelas - 3.99 - Hipercard", "Elo", "    1 Parcela - 2.01 - Elo", "    2 Parcelas - 2.93 - Elo", "    3 Parcelas - 2.93 - Elo", "    4 Parcelas - 2.93 - Elo", "    5 Parcelas - 2.93 - Elo", "    6 Parcelas - 2.93 - Elo", "    7 Parcelas - 3.39 - Elo", "    8 Parcelas - 3.39 - Elo", "    9 Parcelas - 3.39 - Elo", "    10 Parcelas - 3.39 - Elo", "    11 Parcelas - 3.39 - Elo", "    12 Parcelas - 3.39 - Elo", "Cabal Vale", "    1 Parcela - 3.29 - Cabal Vale", "    2 Parcelas - 3.99 - Cabal Vale", "    3 Parcelas - 3.99 - Cabal Vale", "    4 Parcelas - 3.99 - Cabal Vale", "    5 Parcelas - 3.99 - Cabal Vale", "    6 Parcelas - 3.99 - Cabal Vale", "    7 Parcelas - 3.99 - Cabal Vale", "    8 Parcelas - 3.99 - Cabal Vale", "    9 Parcelas - 3.99 - Cabal Vale", "    10 Parcelas - 3.99 - Cabal Vale", "    11 Parcelas - 3.99 - Cabal Vale", "    12 Parcelas - 3.99 - Cabal Vale", "Amex", "    1 Parcela - 3.29 - Amex", "    2 Parcelas - 3.99 - Amex", "    3 Parcelas - 3.99 - Amex", "    4 Parcelas - 3.99 - Amex", "    5 Parcelas - 3.99 - Amex", "    6 Parcelas - 3.99 - Amex", "    7 Parcelas - 3.99 - Amex", "    8 Parcelas - 3.99 - Amex", "    9 Parcelas - 3.99 - Amex", "    10 Parcelas - 3.99 - Amex", "    11 Parcelas - 3.99 - Amex", "    12 Parcelas - 3.99 - Amex" }));
        combobox2cartaocredito.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobox2cartaocreditoItemStateChanged(evt);
            }
        });

        combobox2cartaodebito.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha uma opção de Pagamento", "Mastercard", "    0.77 - Mastercard", "Visa", "    0.77 - Visa", "Hipercard", "    1.47 - Hipercard", "Elo", "    1.42 - Elo", "Cabal Vale", "    1.99 - Cabal Vale", "Amex", "    3.29 - Amex" }));
        combobox2cartaodebito.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobox2cartaodebitoItemStateChanged(evt);
            }
        });

        picpay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                picpayFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("PicPay");

        comboxpicpay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha uma opção de Pagamento", "    Taxa - 1.99" }));
        comboxpicpay.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboxpicpayItemStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Parcelas");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("2 Cartão Débito Fornecedor");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("1 Cartão Débito Fornecedor");

        cparcc1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cparcc1FocusLost(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("1 Cartão Crédito Fornecedor");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("2 Cartão de Crédito Fornecedor");

        cparcc2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cparcc2FocusLost(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Dinheiro");

        dinheiro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dinheiroFocusLost(evt);
            }
        });

        pix.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pixFocusLost(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Pix");

        cparcd1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cparcd1FocusLost(evt);
            }
        });

        cparcd2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cparcd2FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cdebito2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ccredito2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cdebito1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ccredito1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combobox1cartaodebito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combobox2cartaocredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combobox1cartaocredito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combobox2cartaodebito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel15))
                        .addGap(144, 144, 144)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10))
                        .addGap(0, 111, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(cparcc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cparcc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(picpay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dinheiro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(270, 270, 270)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13)
                            .addComponent(comboxpicpay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cparcd1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(cparcd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18)
                            .addComponent(pix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox1cartaocredito, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccredito1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdebito1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox1cartaodebito, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccredito2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox2cartaocredito, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdebito2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox2cartaodebito, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cparcc1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cparcd1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cparcc2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cparcd2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pix, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(picpay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboxpicpay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel4.setBackground(new java.awt.Color(46, 65, 88));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Total da Venda");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Subtotal");

        ck_subtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ck_subtotal.setForeground(new java.awt.Color(0, 102, 51));
        ck_subtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ck_subtotal.setText("R$ 0,00");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ck_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(ck_subtotal))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Desconto");

        ck_desconto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ck_desconto.setForeground(new java.awt.Color(153, 0, 0));
        ck_desconto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ck_desconto.setText("R$ 0,00");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(ck_desconto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(ck_desconto))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Total");

        ck_total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ck_total.setForeground(new java.awt.Color(0, 102, 51));
        ck_total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ck_total.setText("R$ 0,00");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(ck_total, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(ck_total))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Valor a Pagar");

        ck_totalPagar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ck_totalPagar.setForeground(new java.awt.Color(0, 102, 51));
        ck_totalPagar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ck_totalPagar.setText("R$ 0,00");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ck_totalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(ck_totalPagar))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Valor Restante");

        ck_valorRestante.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ck_valorRestante.setForeground(new java.awt.Color(153, 0, 0));
        ck_valorRestante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ck_valorRestante.setText("R$ 0,00");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ck_valorRestante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ck_valorRestante)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("F9 Finalizar Venda");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("ESC Deixar Venda");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("F8 Limpar Campos");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(20, 20, 20)
                .addComponent(jLabel23)
                .addGap(20, 20, 20)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdebito1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cdebito1FocusLost
        calculaVenda(cdebito1.getText());
    }//GEN-LAST:event_cdebito1FocusLost

    private void ccredito2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ccredito2FocusLost
        calculaVenda(ccredito2.getText());
    }//GEN-LAST:event_ccredito2FocusLost

    private void cdebito2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cdebito2FocusLost
        calculaVenda(cdebito2.getText());
    }//GEN-LAST:event_cdebito2FocusLost

    private void cparcc1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cparcc1FocusLost
        calculaVenda(cparcc1.getText());
        mVendaPagamentoCheckout.setCartaoCreditoParceiroHist(cparcc1.getText());
        mVendaPagamentoCheckout.setCartaoCreditoParceiro(cparcc1.getText());
    }//GEN-LAST:event_cparcc1FocusLost

    private void cparcd1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cparcd1FocusLost
        calculaVenda(cparcd1.getText());
        mVendaPagamentoCheckout.setCartaoDebitoParceiroHist(cparcd1.getText());
        mVendaPagamentoCheckout.setCartaoDebitoParceiro(cparcd1.getText());
    }//GEN-LAST:event_cparcd1FocusLost

    private void cparcc2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cparcc2FocusLost
        calculaVenda(cparcc2.getText());
        mVendaPagamentoCheckout.setCartaoDebito2ParceiroHist(cparcc2.getText());
        mVendaPagamentoCheckout.setCartaoDebito2Parceiro(cparcc2.getText());
    }//GEN-LAST:event_cparcc2FocusLost

    private void cparcd2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cparcd2FocusLost
        calculaVenda(cparcd2.getText());
        mVendaPagamentoCheckout.setCartaoCredito2ParceiroHist(cparcd2.getText());
        mVendaPagamentoCheckout.setCartaoCredito2Parceiro(cparcd2.getText());
    }//GEN-LAST:event_cparcd2FocusLost

    private void dinheiroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dinheiroFocusLost
        calculaVenda(dinheiro.getText());
        mVendaPagamentoCheckout.setDinheiro(dinheiro.getText());
    }//GEN-LAST:event_dinheiroFocusLost

    private void pixFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pixFocusLost
        calculaVenda(pix.getText());
        mVendaPagamentoCheckout.setPix(pix.getText());
    }//GEN-LAST:event_pixFocusLost

    private void picpayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_picpayFocusLost
        calculaVenda(picpay.getText());
    }//GEN-LAST:event_picpayFocusLost

    private void ccredito1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ccredito1FocusLost
        calculaVenda(ccredito1.getText());
    }//GEN-LAST:event_ccredito1FocusLost

    // selects de pagamento
    private void combobox1cartaocreditoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobox1cartaocreditoItemStateChanged
        String pg[] = combobox1cartaocredito.getSelectedItem().toString().split("-");
        try {
            float v = Float.parseFloat(ccredito1.getText());
            float t = Float.parseFloat(pg[1].trim());
            float valorTaxa = taxaPag.taxaPagamento(v, t);
            mVendaPagamentoCheckout.setCartaoCreditoLojaHist(ccredito1.getText());
            mVendaPagamentoCheckout.setCartaoCreditoLoja(String.valueOf(valorTaxa));
            mVendaPagamentoCheckout.setParcelaCreditoLoja(pg[0].trim());
            mVendaPagamentoCheckout.setTaxaCreditoLoja(pg[1].trim());
            mVendaPagamentoCheckout.setBandeiraCreditoLoja(pg[2].trim());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_combobox1cartaocreditoItemStateChanged

    private void combobox1cartaodebitoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobox1cartaodebitoItemStateChanged
        String pg[] = combobox1cartaodebito.getSelectedItem().toString().split("-");
        try {
            float v = Float.parseFloat(cdebito1.getText());
            float t = Float.parseFloat(pg[0].trim());
            float valorTaxa = taxaPag.taxaPagamento(v, t);
            mVendaPagamentoCheckout.setCartaoDebitoLojaHist(cdebito1.getText());
            mVendaPagamentoCheckout.setCartaoDebitoLoja(String.valueOf(valorTaxa));
            mVendaPagamentoCheckout.setTaxaDebitoLoja(pg[0].trim());
            mVendaPagamentoCheckout.setBandeiraDebitoLoja(pg[1].trim());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_combobox1cartaodebitoItemStateChanged

    private void combobox2cartaocreditoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobox2cartaocreditoItemStateChanged
        String pg[] = combobox2cartaocredito.getSelectedItem().toString().split("-");
        try {
            float v = Float.parseFloat(ccredito2.getText());
            float t = Float.parseFloat(pg[1].trim());
            float valorTaxa = taxaPag.taxaPagamento(v, t);
            mVendaPagamentoCheckout.setCartaoCredito2LojaHist(ccredito2.getText());
            mVendaPagamentoCheckout.setCartaoCredito2Loja(String.valueOf(valorTaxa));
            mVendaPagamentoCheckout.setParcelaCredito2Loja(pg[0].trim());
            mVendaPagamentoCheckout.setTaxaCredito2Loja(pg[1].trim());
            mVendaPagamentoCheckout.setBandeiraCredito2Loja(pg[2].trim());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_combobox2cartaocreditoItemStateChanged

    private void combobox2cartaodebitoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobox2cartaodebitoItemStateChanged
        String pg[] = combobox2cartaodebito.getSelectedItem().toString().split("-");
        try {
            float v = Float.parseFloat(cdebito2.getText());
            float t = Float.parseFloat(pg[0].trim());
            float valorTaxa = taxaPag.taxaPagamento(v, t);
            mVendaPagamentoCheckout.setCartaoDebito2LojaHist(cdebito2.getText());
            mVendaPagamentoCheckout.setCartaoDebito2Loja(String.valueOf(valorTaxa));
            mVendaPagamentoCheckout.setTaxaDebito2Loja(pg[0].trim());
            mVendaPagamentoCheckout.setBandeiraDebito2Loja(pg[1].trim());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_combobox2cartaodebitoItemStateChanged

    private void comboxpicpayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboxpicpayItemStateChanged
        String pg[] = comboxpicpay.getSelectedItem().toString().split("-");
        try {
            float v = Float.parseFloat(picpay.getText());
            float t = Float.parseFloat(pg[1].trim());
            float valorTaxa = taxaPag.taxaPagamento(v, t);
            mVendaPagamentoCheckout.setPicpayHist(picpay.getText());
            mVendaPagamentoCheckout.setPicpay(String.valueOf(valorTaxa));
            mVendaPagamentoCheckout.setTaxaPicpay(pg[1].trim());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_comboxpicpayItemStateChanged

    public void setCheckoutValores() {
        ck_subtotal.setText(cSbutotal);
        ck_total.setText(cTotal);
        if (cDesconto.equals("")) {
            ck_desconto.setText("0,00");
        } else {
            ck_desconto.setText(cDesconto);
        }

        ck_totalPagar.setText(cTotalPagar);
        ck_valorRestante.setText(cTotalPagar);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightFlatIJTheme.setup();
 
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DvendaManual dialog = new DvendaManual(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dfuncao;
    private javax.swing.JLabel Doperador;
    private componentes.UJTextField ccredito1;
    private componentes.UJTextField ccredito2;
    private componentes.UJTextField cdebito1;
    private componentes.UJTextField cdebito2;
    private javax.swing.JLabel ck_desconto;
    private javax.swing.JLabel ck_subtotal;
    private javax.swing.JLabel ck_total;
    private javax.swing.JLabel ck_totalPagar;
    private javax.swing.JLabel ck_valorRestante;
    private componentes.UJComboBox combobox1cartaocredito;
    private componentes.UJComboBox combobox1cartaodebito;
    private componentes.UJComboBox combobox2cartaocredito;
    private componentes.UJComboBox combobox2cartaodebito;
    private componentes.UJComboBox comboxpicpay;
    private componentes.UJTextField cparcc1;
    private componentes.UJTextField cparcc2;
    private componentes.UJTextField cparcd1;
    private componentes.UJTextField cparcd2;
    private componentes.UJTextField dinheiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private componentes.UJTextField picpay;
    private componentes.UJTextField pix;
    // End of variables declaration//GEN-END:variables

    public void CorComboBox() {
        try {
            combobox1cartaocredito.setRenderer(new Colorir());
            combobox1cartaocredito.setBackground(Color.YELLOW);

            combobox2cartaocredito.setRenderer(new Colorir());
            combobox2cartaocredito.setBackground(Color.YELLOW);

            combobox1cartaodebito.setRenderer(new Colorir());
            combobox1cartaodebito.setBackground(Color.YELLOW);

            combobox2cartaodebito.setRenderer(new Colorir());
            combobox2cartaodebito.setBackground(Color.YELLOW);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void calculaVenda(String param) {
        double valorc, valorDec, result;
        try {
            valorDec = Double.parseDouble(param);
            valorc = Double.parseDouble(ck_valorRestante.getText());
            result = valorc - valorDec;
            ck_valorRestante.setText(String.valueOf(result));
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        }

    }

    class Colorir extends JLabel implements ListCellRenderer {

        public Colorir() {
            super();
            setOpaque(true);
        }

        @Override
        public Component getListCellRendererComponent(JList list, Object value,
                int index, boolean isSelected, boolean cellHasFocus) {
            setText(value.toString());

            Object texto = combobox1cartaocredito.getItemAt(index);
            Object texto2 = combobox2cartaocredito.getItemAt(index);

            Object texto3 = combobox1cartaodebito.getItemAt(index);
            Object texto4 = combobox2cartaodebito.getItemAt(index);

            //**********************************************************************
            setBackground(Color.white);
//            if (texto != null && (texto.toString()) == "Mastercard") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto2 != null && (texto2.toString()) == "Mastercard") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto != null && (texto.toString()) == "Visa") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto2 != null && (texto2.toString()) == "Visa") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto != null && (texto.toString()) == "Hipercard") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto2 != null && (texto2.toString()) == "Hipercard") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto != null && (texto.toString()) == "Elo") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto2 != null && (texto2.toString()) == "Elo") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto != null && (texto.toString()) == "Cabal Vale") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto2 != null && (texto2.toString()) == "Cabal Vale") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto != null && (texto.toString()) == "Amex") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto2 != null && (texto2.toString()) == "Amex") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//            
//            // Debito
//            if (texto3 != null && (texto3.toString()) == "Mastercard") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto4 != null && (texto4.toString()) == "Mastercard") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto3 != null && (texto3.toString()) == "Visa") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto4 != null && (texto4.toString()) == "Visa") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto3 != null && (texto3.toString()) == "Hipercard") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto4 != null && (texto4.toString()) == "Hipercard") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto3 != null && (texto3.toString()) == "Elo") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto4 != null && (texto4.toString()) == "Elo") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto3 != null && (texto3.toString()) == "Cabal Vale") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto4 != null && (texto4.toString()) == "Cabal Vale") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto3 != null && (texto3.toString()) == "Amex") {
//                setBackground(Color.LIGHT_GRAY);
//            }
//
//            if (texto4 != null && (texto4.toString()) == "Amex") {
//                setBackground(Color.LIGHT_GRAY);
//            }

            return this;
        }
    }

    private void setaUsuarioLogado() {
        this.Doperador.setText(ModelSessaoUsuario.nome);
        this.Dfuncao.setText(ModelSessaoUsuario.funcao);
    }

    private void configTeclasAtalho() {

        rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F9, 0), "F9");
        rootPane.getRootPane().getActionMap().put("F9", new AbstractAction("F9") {
            @Override
            public void actionPerformed(ActionEvent e) {
                //Realiza alguma ação ao ser pressionado o F1
//                System.out.println(mVendaPagamentoCheckout.getCartaoCreditoLojaHist());
//                System.out.println(mVendaPagamentoCheckout.getParcelaCreditoLoja());
//                System.out.println(mVendaPagamentoCheckout.getTaxaCreditoLoja());
//                System.out.println(mVendaPagamentoCheckout.getBandeiraCreditoLoja());
                finalizarCancelar = true;
                dispose();
            }
        });
    }

    public boolean salvaPagamentoVenda(int codigoVenda) {

        mVendaPagamentoCheckout.setIdVenda(codigoVenda);
        System.out.println(mVendaPagamentoCheckout);
        if (ctrlVendaPagamentoCheckout.salvarVendasPagamentoController(mVendaPagamentoCheckout) > 0) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * @return the cSbutotal
     */
    public String getcSbutotal() {
        return cSbutotal;
    }

    /**
     * @param cSbutotal the cSbutotal to set
     */
    public void setcSbutotal(String cSbutotal) {
        this.cSbutotal = cSbutotal;
    }

    /**
     * @return the cDesconto
     */
    public String getcDesconto() {
        return cDesconto;
    }

    /**
     * @param cDesconto the cDesconto to set
     */
    public void setcDesconto(String cDesconto) {
        this.cDesconto = cDesconto;
    }

    /**
     * @return the cTotal
     */
    public String getcTotal() {
        return cTotal;
    }

    /**
     * @param cTotal the cTotal to set
     */
    public void setcTotal(String cTotal) {
        this.cTotal = cTotal;
    }

    /**
     * @return the cTotalPagar
     */
    public String getcTotalPagar() {
        return cTotalPagar;
    }

    /**
     * @param cTotalPagar the cTotalPagar to set
     */
    public void setcTotalPagar(String cTotalPagar) {
        this.cTotalPagar = cTotalPagar;
    }

    /**
     * @return the finalizarCancelar
     */
    public boolean isFinalizarCancelar() {
        return finalizarCancelar;
    }

    /**
     * @param finalizarCancelar the finalizarCancelar to set
     */
    public void setFinalizarCancelar(boolean finalizarCancelar) {
        this.finalizarCancelar = finalizarCancelar;
    }
}
