/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import com.formdev.flatlaf.intellijthemes.FlatLightFlatIJTheme;
import controller.ControllerUsuarios;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.KeyStroke;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.ModelUsuarios;

/**
 *
 * @author DEV
 */
public final class TelaUsuarios extends javax.swing.JFrame {

    ModelUsuarios usuario = new ModelUsuarios();
    ControllerUsuarios ctrlUsuario = new ControllerUsuarios();
    ArrayList<ModelUsuarios> listaUsuarios = new ArrayList<>();
    String salvarAtualizar;

    /**
     * Creates new form TelaClientesCorreto
     */
    public TelaUsuarios() {
        initComponents();
        listaUsuarios();
        listaUsuariosInativos();
        habilitarDesabilitarCampos(false);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setRowTableAlign(4);
        setVisualTabela();
        optionsTable();
        configTeclasAtalho();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_usuariosAtivos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btn_cancelar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_novo1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        funcao_usuario = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        email_usuario = new javax.swing.JTextField();
        nome_usuario = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        senha_usuario = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        status_usuario = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela_usuariosInativos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btn_alterar1 = new javax.swing.JButton();
        btn_salvar1 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        cadastro_cliente1 = new javax.swing.JTextField();
        estado_cliente1 = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cidade_araguari1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        bairro_cliente1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        rua_cliente1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        numero_cliente1 = new javax.swing.JTextField();
        cep_cliente1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        email_cliente1 = new javax.swing.JTextField();
        nome_cliente1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        aniversario_cliente1 = new javax.swing.JFormattedTextField();
        telefone_cliente1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");

        jTabbedPane1.setBackground(new java.awt.Color(237, 237, 237));

        jPanel1.setBackground(new java.awt.Color(237, 237, 237));

        jPanel15.setBackground(new java.awt.Color(0, 153, 102));

        jLabel39.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel39.setText("Usuários:");
        jLabel39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel14.setBackground(new java.awt.Color(0, 153, 102));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Usuário:");

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Lucas Vieira");

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Função:");

        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Administrador");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41)
                .addGap(18, 18, 18)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tabela_usuariosAtivos.setBackground(new java.awt.Color(255, 255, 255));
        tabela_usuariosAtivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do Usuário", "Nome", "E-mail de Acesso", "Senha de Acesso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_usuariosAtivos.setFocusable(false);
        tabela_usuariosAtivos.setGridColor(new java.awt.Color(153, 153, 153));
        tabela_usuariosAtivos.setRowHeight(25);
        tabela_usuariosAtivos.setSelectionBackground(new java.awt.Color(0, 153, 102));
        tabela_usuariosAtivos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabela_usuariosAtivos.setShowGrid(true);
        jScrollPane2.setViewportView(tabela_usuariosAtivos);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("F6 Cancelar");

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("F5 Excluir");

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("F4 Editar");

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("F3 Novo Usuário");

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("F2 Salvar ");

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("F7 Detalhes do Usuário");

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("ESC Fecha Tela");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(395, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buttons/cancel.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setIconTextGap(0);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buttons/delete.png"))); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buttons/refresh.png"))); // NOI18N
        btn_alterar.setText("Editar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buttons/check.png"))); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_novo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buttons/plus.png"))); // NOI18N
        btn_novo1.setText("Novo");
        btn_novo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_novo1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_novo1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setText("Função");

        jLabel24.setText("Nome do usuário:");

        jLabel25.setText("E-mail:");

        jLabel26.setText("Senha:");

        jLabel28.setText("Status:");

        status_usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email_usuario)
                            .addComponent(nome_usuario)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(senha_usuario)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(funcao_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(status_usuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel24)
                .addGap(6, 6, 6)
                .addComponent(nome_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel25)
                .addGap(6, 6, 6)
                .addComponent(email_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel26)
                .addGap(6, 6, 6)
                .addComponent(senha_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel28))
                        .addGap(6, 6, 6)
                        .addComponent(funcao_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(status_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Usuários Ativos", jPanel1);

        jPanel2.setBackground(new java.awt.Color(237, 237, 237));

        jPanel16.setBackground(new java.awt.Color(0, 153, 102));

        jLabel44.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel44.setText("Usuários Inativos:");
        jLabel44.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel17.setBackground(new java.awt.Color(0, 153, 102));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Usuário:");

        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Lucas Vieira");

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Função:");

        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Administrador");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel46)
                .addGap(18, 18, 18)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47)
                    .addComponent(jLabel48))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        tabela_usuariosInativos.setBackground(new java.awt.Color(255, 255, 255));
        tabela_usuariosInativos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do Cliente", "Nome", "Telefone", "Data de Aniversário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_usuariosInativos.setFocusable(false);
        tabela_usuariosInativos.setGridColor(new java.awt.Color(153, 153, 153));
        tabela_usuariosInativos.setRowHeight(25);
        tabela_usuariosInativos.setSelectionBackground(new java.awt.Color(0, 153, 102));
        tabela_usuariosInativos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabela_usuariosInativos.setShowGrid(true);
        jScrollPane3.setViewportView(tabela_usuariosInativos);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("F5 Ativar Cliente");

        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("F7 Detalhes do Cliente");

        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("ESC Fecha Tela");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        btn_alterar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buttons/exchange.png"))); // NOI18N
        btn_alterar1.setText("Ativar Cliente");
        btn_alterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterar1ActionPerformed(evt);
            }
        });

        btn_salvar1.setText("Salvar");
        btn_salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_alterar1)
                .addGap(432, 432, 432)
                .addComponent(btn_salvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_alterar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salvar1))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        estado_cliente1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel31.setText("Estado:");

        jLabel32.setText("Data de Cadastro:");

        jLabel33.setText("Cidade:");

        jLabel34.setText("Bairro:");

        jLabel35.setText("Rua");

        jLabel36.setText("Número:");

        jLabel37.setText("Cep:");

        jLabel38.setText("Nome do cliente:");

        jLabel49.setText("E-mail:");

        jLabel50.setText("Telefone:");

        jLabel51.setText("Data de aniversário:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email_cliente1)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(rua_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(numero_cliente1))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(estado_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cadastro_cliente1))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(bairro_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cidade_araguari1))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(jLabel49)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel50)
                                .addGap(102, 102, 102)
                                .addComponent(jLabel51)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel37))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(315, 315, 315)
                                .addComponent(jLabel36))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(182, 182, 182)
                                .addComponent(jLabel33))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(171, 171, 171)
                                .addComponent(jLabel32)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(telefone_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(aniversario_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cep_cliente1))
                    .addComponent(nome_cliente1))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel38)
                .addGap(6, 6, 6)
                .addComponent(nome_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel49)
                .addGap(6, 6, 6)
                .addComponent(email_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel50)
                    .addComponent(jLabel51)
                    .addComponent(jLabel37))
                .addGap(6, 6, 6)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telefone_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aniversario_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cep_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addGap(6, 6, 6)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rua_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel33))
                .addGap(6, 6, 6)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bairro_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidade_araguari1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addGap(6, 6, 6)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estado_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastro_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 567, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Usuários Inativos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        habilitarDesabilitarCampos(false);
        limparCampos();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        int linha = tabela_usuariosAtivos.getSelectedRow();
        int codigoUsuario;
        codigoUsuario = (int) tabela_usuariosAtivos.getValueAt(linha, 0);

//        if (ctrlUsuario.desativaUsuarioController(codigoUsuario)) {
//            JOptionPane.showMessageDialog(this, "Usuário inativado com Sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
//            this.listaUsuarios();
//            this.listaUsuariosInativos();
//            this.jTabbedPane1.setSelectedIndex(1);
//            this.habilitarDesabilitarCampos(false);
//        } else {
//            JOptionPane.showMessageDialog(this, "Erro ao inativar usuario.", "Aviso", JOptionPane.ERROR_MESSAGE);
//        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        salvarAtualizar = "alterar";
        int linha = tabela_usuariosAtivos.getSelectedRow();

        try {
            int codigoUsuario;
            codigoUsuario = (int) tabela_usuariosAtivos.getValueAt(linha, 0);

            //recupera o produto
            usuario = ctrlUsuario.getUsuariosController(codigoUsuario);
            // set na interface
//            this.nome_usuario.setText(usuario.getNomeUser());
//            this.email_usuario.setText(usuario.getEmailUser());
//            this.senha_usuario.setText(usuario.getSenha());
            this.funcao_usuario.setSelectedItem(usuario.getIdPermissao());
            this.habilitarDesabilitarCampos(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum usuario selecionado", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        if (salvarAtualizar.equals("salvar")) {
            this.salvarUsuario();
        } else if (salvarAtualizar.equals("alterar")) {
            this.alterarCliente();
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_novo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo1ActionPerformed
        salvarAtualizar = "salvar";
        habilitarDesabilitarCampos(true);
        limparCampos();
    }//GEN-LAST:event_btn_novo1ActionPerformed

    private void btn_alterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterar1ActionPerformed
        salvarAtualizar = "alterar";
        int linha = tabela_usuariosAtivos.getSelectedRow();

        try {
            int codigoUsuario;
            codigoUsuario = (int) tabela_usuariosAtivos.getValueAt(linha, 0);

            //recupera o produto
            usuario = ctrlUsuario.getUsuariosController(codigoUsuario);
            // set na interface
//            this.nome_usuario.setText(usuario.getNomeUser());
//            this.email_usuario.setText(usuario.getEmailUser());
//            this.senha_usuario.setText(usuario.getSenha());
            this.funcao_usuario.setSelectedItem(usuario.getIdPermissao());
            this.habilitarDesabilitarCampos(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum usuario selecionado", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_alterar1ActionPerformed

    private void btn_salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar1ActionPerformed
        if (salvarAtualizar.equals("salvar")) {
            this.salvarUsuario();
        } else if (salvarAtualizar.equals("alterar")) {
            this.alterarCliente();
        }
    }//GEN-LAST:event_btn_salvar1ActionPerformed

    public void listaUsuarios() {
        listaUsuarios = ctrlUsuario.getListaUsuariosController();
        DefaultTableModel model = (DefaultTableModel) tabela_usuariosAtivos.getModel();
        model.setNumRows(0);
        int count = listaUsuarios.size();
        for (int i = 0; i < count; i++) {
            model.addRow(new Object[]{
                listaUsuarios.get(i).getIdUser(),
//                listaUsuarios.get(i).getNomeUser(),
//                listaUsuarios.get(i).getEmailUser(),
//                listaUsuarios.get(i).getSenha(),
            });
        }
    }

    public void listaUsuariosInativos() {
//        listaUsuarios = ctrlUsuario.getListaUsuariosInativosController();
//        DefaultTableModel modelTwo = (DefaultTableModel) tabela_usuariosInativos.getModel();
//        modelTwo.setNumRows(0);
//        int count = listaUsuarios.size();
//        for (int i = 0; i < count; i++) {
//            modelTwo.addRow(new Object[]{
//                listaUsuarios.get(i).getIdUser(),
//                listaUsuarios.get(i).getNomeUser(),
//                listaUsuarios.get(i).getEmailUser(),
//                listaUsuarios.get(i).getSenha(),});
//        }
    }

    public void habilitarDesabilitarCampos(boolean condicao) {
        this.nome_usuario.setEnabled(condicao);
        this.email_usuario.setEnabled(condicao);
        this.senha_usuario.setEnabled(condicao);
        this.funcao_usuario.setEnabled(condicao);
        this.btn_salvar.setEnabled(condicao);
    }

    public void limparCampos() {
        this.nome_usuario.setText("");
        this.email_usuario.setText("");
        this.senha_usuario.setText("");
    }

    private void salvarUsuario() {

        usuario.setIdPermissao((int) funcao_usuario.getSelectedItem());
//        usuario.setNomeUser(nome_usuario.getText());
//        usuario.setEmailUser(email_usuario.getText());
//        usuario.setSenha(senha_usuario.getText());
        usuario.setStatus((int) status_usuario.getSelectedItem());


        if (ctrlUsuario.salvarUsuariosController(usuario) > 0) {
            JOptionPane.showMessageDialog(this, "Usuário Cadastrado com Sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            this.listaUsuarios();
            this.habilitarDesabilitarCampos(false);
            this.limparCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao Cadastrar usuário.", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void alterarCliente() {

        usuario.setIdPermissao((int) funcao_usuario.getSelectedItem());
//        usuario.setNomeUser(nome_usuario.getText());
//        usuario.setEmailUser(email_usuario.getText());
//        usuario.setSenha(senha_usuario.getText());
        usuario.setStatus((int) status_usuario.getSelectedItem());

        if (ctrlUsuario.atualizarUsuariosController(usuario)) {
            JOptionPane.showMessageDialog(this, "Usuário Atualizado com Sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            this.listaUsuarios();
            this.habilitarDesabilitarCampos(false);
            this.limparCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao Atualizar usuário.", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void setVisualTabela() {
        // configuração do header da tabela
        tabela_usuariosAtivos.getTableHeader().setBackground(new Color(100, 100, 100));
        tabela_usuariosAtivos.getTableHeader().setForeground(Color.white);

        JTableHeader header = (JTableHeader) tabela_usuariosAtivos.getTableHeader();
        DefaultTableCellRenderer centralizado = (DefaultTableCellRenderer) header.getDefaultRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.LEFT);
    }

    private void setRowTableAlign(int size) {
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.LEFT);

        for (int i = 0; i < size; i++) {
            tabela_usuariosAtivos.getColumnModel().getColumn(i).setCellRenderer(centralizado);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightFlatIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField aniversario_cliente1;
    private javax.swing.JTextField bairro_cliente1;
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_alterar1;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo1;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_salvar1;
    private javax.swing.JTextField cadastro_cliente1;
    private javax.swing.JTextField cep_cliente1;
    private javax.swing.JTextField cidade_araguari1;
    private javax.swing.JTextField email_cliente1;
    private javax.swing.JTextField email_usuario;
    private javax.swing.JComboBox<String> estado_cliente1;
    private javax.swing.JComboBox<String> funcao_usuario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField nome_cliente1;
    private javax.swing.JTextField nome_usuario;
    private javax.swing.JTextField numero_cliente1;
    private javax.swing.JTextField rua_cliente1;
    private javax.swing.JTextField senha_usuario;
    private javax.swing.JComboBox<String> status_usuario;
    private javax.swing.JTable tabela_usuariosAtivos;
    private javax.swing.JTable tabela_usuariosInativos;
    private javax.swing.JTextField telefone_cliente1;
    // End of variables declaration//GEN-END:variables

    private void optionsTable() {
        JPopupMenu jPopupMenu = new JPopupMenu();
        JMenuItem jMenuItemAlterar = new JMenuItem();
        jMenuItemAlterar.setText("Alterar");

        jMenuItemAlterar.addActionListener(new java.awt.event.ActionListener() {
            // Importe a classe java.awt.event.ActionEvent
            @Override
            public void actionPerformed(ActionEvent e) {
                int index = tabela_usuariosAtivos.getSelectedRow();
                // Faça alguma coisa com o item selecionado 
                setEditUsuario();
            }
        });

        JMenuItem jMenuItemExcluir = new JMenuItem();
        jMenuItemExcluir.setText("Excluir");
        jMenuItemExcluir.addActionListener(new java.awt.event.ActionListener() {
            // Importe a classe java.awt.event.ActionEvent
            @Override
            public void actionPerformed(ActionEvent e) {
                int index = tabela_usuariosAtivos.getSelectedRow();
                // Faça alguma coisa com o item selecionado
                desativaUsuarioMouse();
            }
        });

        JMenuItem jMenuItemDetalhes = new JMenuItem();
        jMenuItemDetalhes.setText("Ver Dados do Cliente");
        jMenuItemDetalhes.addActionListener(new java.awt.event.ActionListener() {
            // Importe a classe java.awt.event.ActionEvent
            @Override
            public void actionPerformed(ActionEvent e) {
                int index = tabela_usuariosAtivos.getSelectedRow();
                // Faça alguma coisa com o item selecionado
//                MClientes dialog = new MClientes(new javax.swing.JFrame(), true);
//                dialog.setVisible(true);
            }
        });

        jPopupMenu.add(jMenuItemAlterar);
        jPopupMenu.add(jMenuItemExcluir);
        jPopupMenu.add(jMenuItemDetalhes);

        tabela_usuariosAtivos.addMouseListener(new java.awt.event.MouseAdapter() {
            //Importe a classe java.awt.event.MouseEvent
            @Override
            public void mouseClicked(MouseEvent e) {
                // Se o botão direito do mouse foi pressionado
                if (e.getButton() == MouseEvent.BUTTON3) {
                    // Exibe o popup menu na posição do mouse.
                    jPopupMenu.show(tabela_usuariosAtivos, e.getX(), e.getY());
                }
            }
        });
    }

    private void setEditUsuario() {
        salvarAtualizar = "alterar";

        int linha;
        linha = tabela_usuariosAtivos.getSelectedRow();

        try {
            int codigoUsuario;
            codigoUsuario = (int) tabela_usuariosAtivos.getValueAt(linha, 0);

            // recupera o produto
            usuario = ctrlUsuario.getUsuariosController(codigoUsuario);
            // set na interface
            this.funcao_usuario.setSelectedItem(usuario.getIdPermissao());
//            this.nome_usuario.setText(usuario.getNomeUser());
//            this.email_usuario.setText(usuario.getEmailUser());
//            this.senha_usuario.setText(usuario.getSenha());
            this.status_usuario.setSelectedItem(usuario.getStatus());

            this.habilitarDesabilitarCampos(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum usuario selecionado", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void desativaUsuarioMouse() {
        int linha = tabela_usuariosAtivos.getSelectedRow();
        int codigoUsuario;
        codigoUsuario = (int) tabela_usuariosAtivos.getValueAt(linha, 0);

//        if (ctrlUsuario.desativaUsuarioController(codigoUsuario)) {
//            JOptionPane.showMessageDialog(this, "Usuário inativado com Sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
//            this.listaUsuarios();
//            this.listaUsuariosInativos();
//            this.limparCampos();
//            this.habilitarDesabilitarCampos(false);
//            this.jTabbedPane1.setSelectedIndex(1);
//        } else {
//            JOptionPane.showMessageDialog(this, "Erro ao inativar usuário.", "Aviso", JOptionPane.ERROR_MESSAGE);
//        }
    }
    
    private void ativaUsuario() {
        int linha = tabela_usuariosInativos.getSelectedRow();
        int codigoUsuario;
        codigoUsuario = (int) tabela_usuariosInativos.getValueAt(linha, 0);

//        if (ctrlUsuario.ativarUsuarioController(codigoUsuario)) {
//            JOptionPane.showMessageDialog(this, "Usuário ativado com Sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
//            this.listaUsuarios();
//            this.listaUsuariosInativos();
//            this.limparCampos();
//            this.habilitarDesabilitarCampos(false);
//            this.jTabbedPane1.setSelectedIndex(1);
//        } else {
//            JOptionPane.showMessageDialog(this, "Erro ao ativar usuario.", "Aviso", JOptionPane.ERROR_MESSAGE);
//        }
    }

    private void configTeclasAtalho() {
        rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        rootPane.getRootPane().getActionMap().put("ESCAPE", new AbstractAction("ESCAPE") {
            @Override
            public void actionPerformed(ActionEvent e) {
                //Realiza alguma ação ao ser pressionado o ESC
                dispose();
            }
        });

        rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0), "F2");
        rootPane.getRootPane().getActionMap().put("F2", new AbstractAction("F2") {
            @Override
            public void actionPerformed(ActionEvent e) {
                //Realiza alguma ação ao ser pressionado o F1
                salvarUsuario();
            }
        });

        rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0), "F3");
        rootPane.getRootPane().getActionMap().put("F3", new AbstractAction("F3") {
            @Override
            public void actionPerformed(ActionEvent e) {
                //Realiza alguma ação ao ser pressionado o F1
                salvarAtualizar = "salvar";
                habilitarDesabilitarCampos(true);
                limparCampos();
            }
        });

        rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F4, 0), "F4");
        rootPane.getRootPane().getActionMap().put("F4", new AbstractAction("F4") {
            @Override
            public void actionPerformed(ActionEvent e) {
                //Realiza alguma ação ao ser pressionado o F1
                setEditUsuario();
            }
        });

        rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0), "F5");
        rootPane.getRootPane().getActionMap().put("F5", new AbstractAction("F5") {
            @Override
            public void actionPerformed(ActionEvent e) {
                //Realiza alguma ação ao ser pressionado o F1
                int linha;
                if (jTabbedPane1.getSelectedIndex() == 0) {
                    desativaUsuarioMouse();
                } else {
                    ativaUsuario();
                }
            }
        });

        rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F6, 0), "F6");
        rootPane.getRootPane().getActionMap().put("F6", new AbstractAction("F6") {
            @Override
            public void actionPerformed(ActionEvent e) {
                //Realiza alguma ação ao ser pressionado o F1
                habilitarDesabilitarCampos(false);
                limparCampos();
            }
        });

        rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_F7, 0), "F7");
        rootPane.getRootPane().getActionMap().put("F7", new AbstractAction("F7") {
            @Override
            public void actionPerformed(ActionEvent e) {
                //Realiza alguma ação ao ser pressionado o F1
                int linha = tabela_usuariosAtivos.getSelectedRow();
                if (linha > 0) {
//                    MClientes dialog = new MClientes(new javax.swing.JFrame(), true);
//                    dialog.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Para ver detalhes do usuario selecione um usuario.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        });
    }
}
